<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-6O2J91O" name="tests.global.footer.FooterTest" tests="4" failures="1" timestamp="2022-09-27T22:06:12 ICT" time="17.120" errors="0">
  <testcase name="testFooterLoginPage" time="0.003" classname="tests.global.footer.FooterTest"/>
  <system-out/>
  <testcase name="testFooterHomePage" time="0.002" classname="tests.global.footer.FooterTest"/>
  <system-out/>
  <testcase name="testFooterCategoryPage" time="16.132" classname="tests.global.footer.FooterTest"/>
  <system-out/>
  <testcase name="testFooterRegisterPage" time="0.983" classname="tests.global.footer.FooterTest">
    <failure type="java.lang.AssertionError" message="Demo taking screenshot when test is failed!">
      <![CDATA[java.lang.AssertionError: Demo taking screenshot when test is failed!
at org.testng.Assert.fail(Assert.java:110)
at tests.global.footer.FooterTest.testFooterRegisterPage(FooterTest.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:32)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:467)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- testFooterRegisterPage -->
  <system-out/>
</testsuite> <!-- tests.global.footer.FooterTest -->
